### ISSUE TITLE
安装库时候没有没有正确拷贝文件

### ISSUE THREAD

**Issue by zx490336534** [nanoric/c2py#8]
c2py版本：`0.5.5`
安装方法：将c2py克隆至本地，在文件夹中使用`python setup.py build`和`python setup install`
完成`REAMME.md`中的例子需要进行如下操作：
1. 运行 `c2py\tests\generate\ctp\generate_ctp.sh`
2. 拷贝` c2py\3rd_party` 到 `python3\Lib\site-packages\c2py-0.5.5-py3.7.egg`
3. 拷贝 `c2py\c2py\include` 到 `python3\Lib\site-packages\c2py-0.5.5-py3.7.egg\c2py`
4. 运行 `python setup.py build`
5. 运行 `python setup.py install`
6. 拷贝 `c2py\tests\generate\ctp\vnctp`下的dll文件到`python3\Lib\site-packages\vnctp-1.0.0-py3.7-win-amd64.egg`
7. 运行 python 输入 `import vnctp`

**Comment by shiniantianlang** [comment]
ctp目录下面没有setup.py文件，请问是怎么安装vnctp的呢？

**Comment by zx490336534** [comment]
运行了sh会生成的

**Comment by nanoric** [comment]
安装不属于c2py要考虑的范畴。
